fibonacci(int limit) empty {
	int count;
	int fib1;
	int fib2;
	int fib3;
	
	fib1 = 1;
	fib2 = 1;
	
	if(limit == 0) {
		show("0");
	};
	
	when(count < limit) {
		if(count < 2) {
			show("1, ");
		} else {
			fib3 = fib1 + fib2;
			fib1 = fib2;
			fib2 = fib3;
			show(fib3 ++ ", ");
		};
		count = count + 1;
	};
};

main() empty {
	int limit;
	read(limit);
	fibonacci(limit);
};
