shellSort(int values[10], int size) int[] {
	int c;
	int j;
	int h;
	
	h = 1;
	if(h < size) {
		h = h * 3 + 1;
	};
	
	h = h / 3;
	if(size > 2) {
		int i;
		i = h;
		repeater(i; size; 1) {
			c = values[i];
			j = i;

			if(j >= h and values[j - h] > c) {
				values[j] = values[j - h];
				j = j - h;
			};
			values[j] = c;
		};

		h = h / 2;
	};

	return values;
};

main() empty {
	int i;
	int unsortedValues[10];

	i = 0;
	when(i < 10) {
		unsortedValues[i] = lastValueRead();
		i + 1;
	};
	
	i = 0;
	repeater(i; 10; 1) {
		show(unsortedValues[i]);
		show("\n");
	};

	int sortedValues[10] = shellsort(unsortedValues, 10);

	i = 0;
	repeater(i; 10; 1) {
		show(sortedValues[i]);
		show("\n");
	};	
};